### ISSUE TITLE
How to add files to the CDN?

### ISSUE THREAD

**Issue by Vadorequest** [thabo-lebelo/on-demand-videos#1]
Thanks for the article and OSS repo.

I've read through the code and it seems all this do is to create the "videos" CDN in CloudFront, it doesn't actually do any file uploading, does it?

I'm looking for a way to:
1. Easily boostrap the whole AWS config (which seems this repo does)
1. Consume an API endpoint where I'd provide the filename and file itself for it to be uploaded into AWS under the path I provided

I feel like this second point is not possible using this implementation, or did I miss something?

**Comment by thabo-lebelo** [comment]
Thanks for the feedback... The article just focuses on just creating a CDN (you're correct). The file was manually uploaded using the AWS console.

To programatically upload a file, you can create an API endpoint and consume it from your application. I have done something similar in the article below:

[Secure S3 Objects Using a Presigned URL](https://thabolebelo.com/secure-s3-objects-using-a-presigned-url/)

**Comment by Vadorequest** [comment]
Thanks! I'll try to use something a bit more "low-code" with PipeDream, makes some things easier, such as storing S3 images from image url, etc.
